
- include_vars: mysql.yml

- name: Installera senaaste mariaDB och Mysql-python lib
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - mariadb
    - MySQL-python


- name: Starta mariadb
  service:
    name: mariadb
    enabled: yes
    state: started

- name: Skapar databas
  mysql_db:
    name: webappdb
    state: present

- name: Kopierar databas
  copy:
    src: "webbapp.sql"
    dest: "/"


- name: Restore database
  mysql_db:
    name: webappdb
    state: import
    target: /webbapp.sql



- name: Cleanup
  file:
    path: /webbapp.sql
    state: absent


- name: Skapar user
  mysql_user:
    name: webappuser
    password: "{{mysql_password}}"
    priv: '*.*:ALL,GRANT'
    host: "{{ hostvars[groups['webb'][0]]['ansible_eth0']['ipv4']['address'] }}"
    state: present
    

